# Generated by Django 4.0.2 on 2022-02-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_cpf_profile_identification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
