# Generated by Django 3.2.8 on 2021-11-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite seu nome completo', max_length=50)),
                ('identification', models.DateField(help_text='Informe seu CPF')),
                ('state', models.CharField(help_text='Informe seu estado', max_length=100)),
                ('city', models.CharField(help_text='Informe sua cidade', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
