# Generated by Django 3.2.8 on 2021-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_operator_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identification',
            field=models.CharField(help_text='Informe seu cpf', max_length=11),
        ),
    ]
