# Generated by Django 4.0.2 on 2022-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_alter_operator_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='stage',
            field=models.CharField(help_text='Informe o CPF do operador', max_length=50),
        ),
    ]
